### ISSUE TITLE
Allow download-workshop to be run in container to update content.

### ISSUE THREAD

**Issue by GrahamDumpleton** [eduk8s/workshop-dashboard#21]
The ``download-workshop`` script is used to pull content down when the container starts. The content is placed at ``/opt/eduk8s/workshop``. Change the script so that it detects when that target directory already exists and provide option to replace the existing content and for good measure restart the content renderer as well. In effect, the same steps as:

```
mv /opt/eduk8s/workshop /opt/eduk8s/workshop.old
download-workshop github.com/eduk8s-tests/lab-sample-workshop
supervisorctl restart workshop
```

Will need to verify that ``supervisorctl restart workshop`` does work as have had issues with doing restarts of it in past as the node express app will not shutdown properly.

Do note though that this will not trigger changed setup steps in ``workshop/environment`` or ``workshop/setup.d``.

Worth noting though is that if training portal configuration of:

```
apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-sample-workshop
spec:
  portal:
    capacity: 1
    reserved: 1
    expires: 60m
    orphaned: 5m
  workshops:
  - name: lab-sample-workshop
```

is used. In particular if have expires/orphaned, then restarting workshop results in workshop container being stopped. When start over, get fresh content pulled from GitHub. If were using image for workshop, would be same provided that image was rebuilt with newer content.
